const ACTIONS = Object.freeze({
  ADD_MY_BEER: "ADD_MY_BEER",
  INIT_MY_BEERS: "INIT_MY_BEERS",
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
  SET_IS_SHOW_ADD_BEER_MOBEL: "SET_IS_SHOW_ADD_BEER_MOBEL",
});

export default ACTIONS;
